name = "RuiRojo-public"
uuid = "c9b51bb6-9077-4eaf-b8bf-9621aa8ad7d4"
repo = "https://github.com/pakaca/julia-registry-rui"

[packages]
b2830079-5d0a-461a-85e0-6b6445f889a9 = { name = "Geo", path = "G/Geo" }
